### ISSUE TITLE
createSizedImageNode duplication

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/make-a-ten#108]
This particular bit of code looks to be duplicated both in Vegas' LevelSelectionButton, making-tens' LevelSelectionButton, and MakingTensUtil.

In the Vegas (original?), it has this note:
> TODO: Consider making this commonly accessible (or finding a better way to do it).

Presumably this behavior should be somewhere like scenery-phet, and it should only adjust the localBounds of the image node (instead of creating an extra rectangle). It would also be ideal for its bounds to always be of the input size. @jbphet and @pixelzoom, does this sound acceptable? (I can create a common-code issue if it is)

Also @AshrafSharf, are there any making-tens-specific modifications made in the two implementations in making-tens?

**Comment by pixelzoom** [comment]
Factoring out createSizedImageNode into something else in scenery-phet sounds good.

I also question the copying of vegas.LevelSelectionNode to making-tens.LevelSelectionNode, whose doc says:

```js
* The Vegas LevelSelectionButton is copied over to MakingTens, because of the need to display
* the score in "Text", next  to the star symbol.
```

Copying is not acceptable in this case.  Other solutions to investigate, in this order:

(1) Push back on the "text next to stars" requirement. Why is it needed in this sim, but not in others?
(2) Investigate subtyping and decorating vegas.LevelSelectionButton.
(3) Add the "text next to stars" feature to vegas.LevelSelectionButton.

**Comment by jonathanolson** [comment]
> Copying is not acceptable in this case.

Agreed. I have issues open for all code duplication I found, namely #108, #81, #80 and #76. (notably https://github.com/phetsims/making-tens/issues/81 is for all of LevelSelectionButton).

> (1) Push back on the "text next to stars" requirement. Why is it needed in this sim, but not in others?

Each level has an unlimited number of challenges, so it essentially counts "how many correct answers so far" per level. @amanda-phet or @bethstade would need to be the ones to comment on the reasoning.

> (2) Investigate subtyping and decorating vegas.LevelSelectionButton.
> (3) Add the "text next to stars" feature to vegas.LevelSelectionButton.

@ariel-phet, does this seem like a common pattern we'll use for games, or a one-off for this sim? If it's recurring, (3) sounds better. Otherwise, (2) may be better.

**Comment by ariel-phet** [comment]
@jonathanolson hard to say for sure, but most games we have made thus far have a definite number of challenges on each level (to my knowledge this is the only one of its kind and no others that I know are planned).

It seems (2) is the correct option in this case

**Comment by bethstade** [comment]
There are actually no incorrect answers, since you can't actually do anything wrong if you get the numbers together.  You can "not" finish, by exiting the challenge, but that should not count "against you."
I believe the stars are a measure how how many challenges completed (not sure what we specified, 10 or 20?) and then you can play the challenges forever.  Again, with the idea that these are "intervention" levels to allow practice of specific skills, not game levels.

**Comment by amanda-phet** [comment]
The number of challenges you can play in this sim are “infinite”. We can have a cutoff, but in the design we never discussed a maximum number of stars. I would not cut off at 10 or 20 though. Maybe 200?


On Mar 1, 2016, at 7:05 AM, bethstade <notifications@github.com<mailto:notifications@github.com>> wrote:


There are actually no incorrect answers, since you can't actually do anything wrong if you get the numbers together. You can "not" finish, by exiting the challenge, but that should not count "against you."
I believe the stars are a measure how how many challenges completed (not sure what we specified, 10 or 20?) and then you can play the challenges forever. Again, with the idea that these are "intervention" levels to allow practice of specific skills, not game levels.

**Comment by jbphet** [comment]
+1 for factoring out ```createSizedImageNode```.  Also agree that it would be better to extend/reuse the existing code than to leave the copied code.

**Comment by jonathanolson** [comment]
@AshrafSharf, let's discuss this during our meeting.
