### ISSUE TITLE
Potential change to drag behavior

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/make-a-ten#240]
When the user drags to split a number into two numbers, there are some advantages of repositioning the dragged number so that the mouse is over the "drag-to-move" part of the number instead of the "drag-to-split" part.

This comes up in cases like:

1. User clicks and drags to split 100 into 90 and 10 (currently dragging the 10)
2. User releases the 10 and immediately re-grabs it without moving the mouse at all.
3. This pulls off a 1 instead of allowing the user to adjust the placement of the 10.

Where the user might expect:

1. User clicks and drags to split 100 into 90 and 10 (currently dragging the 10). The 10 repositions itself so that the mouse is over the bottom area (where it would be moved)
2. User releases the 10 and immediately re-grabs it without moving the mouse at all.
3. This continues moving the 10, as the mouse is over the lower area of the number already.

Thoughts?

**Comment by bethstade** [comment]
this would be a terrific enhancement as it does occur fairly often that the extra one gets pulled off.
I would love to see this implemented.
Can't really think if any downside.

----- Original Message -----From: Jonathan Olson <notifications@github.com>To: phetsims/make-a-ten <make-a-ten@noreply.github.com>Sent: Thu, 20 Oct 2016 18:50:56 -0000 (UTC)Subject: [phetsims/make-a-ten] Potential change to drag behavior (#240)

When the user drags to split a number into two numbers, there are some advantages of repositioning the dragged number so that the mouse is over the "drag-to-move" part of the number instead of the "drag-to-split" part.
This comes up in cases like:

User clicks and drags to split 100 into 90 and 10 (currently dragging the 10)
User releases the 10 and immediately re-grabs it without moving the mouse at all.
This pulls off a 1 instead of allowing the user to adjust the placement of the 10.

Where the user might expect:

User clicks and drags to split 100 into 90 and 10 (currently dragging the 10). The 10 repositions itself so that the mouse is over the bottom area (where it would be moved)
User releases the 10 and immediately re-grabs it without moving the mouse at all.
This continues moving the 10, as the mouse is over the lower area of the number already.

Thoughts?
&mdash;You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by amanda-phet** [comment]
I'm curious to see what this ends up looking like... I have some concern that the number could appear too jumpy if it is repositioning itself, but the way you describe it sounds very intuitive. 

Thanks for the suggestion. Since @bethstade is also on board I think you can go ahead and implement it!

**Comment by jonathanolson** [comment]
Changes made, let me know how it behaves.

**Comment by bethstade** [comment]
Are the new touch areas implemented also?
We should try this with the new number touch areas too.

**Comment by jonathanolson** [comment]
The "touch outside but close to the number" isn't implemented yet (that's https://github.com/phetsims/make-a-ten/issues/16), but the current areas should work on touch devices.

**Comment by bethstade** [comment]
I had a chance to look at this with Kathy this morning.  Very very jumpy and really loses the very important feel of pulling apart the number.  We suggest not implementing this change and sticking with the occasional "accidental" pull apart.

**Comment by jonathanolson** [comment]
Changed behavior to remove the shift (see http://phettest.colorado.edu/make-a-ten/make-a-ten_en.html?ea&brand=phet).

Closing.
