### ISSUE TITLE
Number alignment seems off

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/make-a-ten#247]
Because of the transparency settings, it is really obvious that something is off here: 

![screen shot 2016-11-01 at 3 22 07 pm](https://cloud.githubusercontent.com/assets/7852916/19908077/42157b9e-a047-11e6-8768-2414dc779759.png)

The numbers should be aligned so that the 0s completely overlap each other. I'm not sure if this issue arose because the artwork was changed slightly (#241), or if the alignment settings changed. 

It seems to be more of a problem for 10-60 and less of a problem for 70-90.

**Comment by jonathanolson** [comment]
The original assets and exported images had large differences in the placements of both the zeros and non-zero digits (along with image size differences and alignment differences) that would have made it very difficult to handle aligning the zeros.

Thus I've rebuilt the paper numbers by separating them into digit images (0-9) and paper backgrounds (1-4 digits long), so that all of the alignment would work out correctly.

This seems to be working well (please try the current master version), although there are many digit variations that we could look into getting rid of. For example, the 7 in '70' is farther to the left than any other 7, and similarly with the 9 in '90' (seems unintentional?). The '1' has a very different position for the 1 than '10' (which I believe is intentional).

It would be good to discuss removing these digit-place specific offsets, and what is flexible to change for consistency.

For reference, the current offsets (determined by comparing each digit in each position to the original):
```js
    0: { 1: -61, 2: -3, 3: -6, 4: 4, 5: 5, 6: 2, 7: 19, 8: 12, 9: 16 },
    1: { 1: 4, 2: 7, 3: 4, 4: 0, 5: -2, 6: -1, 7: -13, 8: -8, 9: -13 },
    2: { 1: -4, 2: -1, 3: 0, 4: -3, 5: -2, 6: -2, 7: -3, 8: -1, 9: -1 },
    3: { 1: -1, 2: -2, 3: 1, 4: -3, 5: -3, 6: -1, 7: -2, 8: -3, 9: -3 }
```
Where the first row is for 1-digit numbers, 2nd row for 2-digit numbers, etc. Thus the '1' is shifted to the left significantly in the single-digit '1' (by -61), but shifted slightly to the right for '10' (by 4). '9' has the 9 shifted to the right by 16, to the left by -13 in '90', and is close to unshifted for '900' and '9000', etc. It would be great to have all (or most, given the exception for '1'?) of these be 0.

**Comment by amanda-phet** [comment]
>For example, the 7 in '70' is farther to the left than any other 7, and similarly with the 9 in '90' (seems unintentional?). 
I think this was intentional... because 7 is a wide number, and if you don't offset it and build, say 750, the paper 50 would partially cover the 7. If you don't offset the 7, and this is not the case, then I don't see a reason not to remove the offset. 

>The '1' has a very different position for the 1 than '10' (which I believe is intentional).
Yes, very intentional. Numbers like 21 and 31 look odd if the 1 is too far right, but numbers like 17 and 18 look odd if the 1 is too far left. 

Should we just try offset=0 for all numbers (except 1) and see how they look?

**Comment by jonathanolson** [comment]
Master now removed most offsets (kept some on the single digits). There are no per-digit customized offsets for anything but single digits.

Let me know how it looks (phettest), particularly the 10s, 100s and 1000s (we can reposition single digits easily).

**Comment by amanda-phet** [comment]
It looks good to me, and I didn't notice anything strange during interviews last week.
