### ISSUE TITLE
Add logic to prevent duplicate, back-to-back questions in the game

### ISSUE THREAD

**Issue by phet-steele** [phetsims/make-a-ten#270]
This probably isn't a big deal since it seems to be rare. However, with that being said, it happens quite often in level 2 since one of the numbers is fixed and increases the chance of duplicates. You probably didn't need a video to know what I'm talking about, but here it is anyway 😄 :
![mat05](https://cloud.githubusercontent.com/assets/5863899/22527203/7ff495a8-e88b-11e6-8bfe-8e52e181b853.gif)

@amanda-phet this decision is yours. We have added logic in other sims to prevent this sort of thing before, but again it's rare in this sim (except level 2).

For phetsims/tasks#767.

**Comment by amanda-phet** [comment]
Thanks for pointing this out, but I'm not too worried about this scenario. The point of this level is to figure out how to take 1 off a number and add it to 9 to get 10. These levels are intended to isolate specific skills, and if someone has mastered the skill then they don't have to play the level (since we can't "complete" levels in this sim).
