### ISSUE TITLE
Change behavior of number readouts on Adding screen

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/make-a-ten#272]
Per 2/2/17 discussion: 

On startup there should be a dashed outline for each number that has not yet been entered. ANY time this number is empty we see a dashed outline in place of a number (such as when a user deletes a previously entered number). 
![screen shot 2017-02-03 at 12 02 50 pm](https://cloud.githubusercontent.com/assets/7852916/22604517/32cbafd0-ea09-11e6-9362-3bb37c3d9d9a.png)

When actively editing a number, a white background should be in the rectangle.
![screen shot 2017-02-03 at 12 02 34 pm](https://cloud.githubusercontent.com/assets/7852916/22604512/2de0e724-ea09-11e6-813f-eaa87ea3e04f.png)

Once a number has been entered, the rectangle is not visible:
![screen shot 2017-02-03 at 12 08 49 pm](https://cloud.githubusercontent.com/assets/7852916/22604593/8bf50426-ea09-11e6-9325-545ee1b5c677.png)

**Comment by jonathanolson** [comment]
To clarify, what happens when a number has been previously entered (say in the left), and the user goes back to edit it? When they open the (what will be modal) keypad for it, should it:

1. Keep the old number in the readout (like currently), and have a dashed box with white background (so `ANY time this number is empty we see a dashed outline` isn't an "if and only if").
2. Keep the old number in the readout (like currently), with no dashed box (and thus no background).
3. Remove the old number in the readout, and have a dashed box with white background.

**Comment by amanda-phet** [comment]
Option 1 seems best so that if a user accidentally clicks the edit button they can dismiss it without repercussions. The number should only be empty (and thus have a dashed outline with no white fill) on startup or if a user deletes a number then dismisses the keypad.

**Comment by jonathanolson** [comment]
Implemented, does that look good?

**Comment by amanda-phet** [comment]
It does look good. The one unfortunate thing is that the dimmed background makes the white background less apparent, but it seems fine. The behavior that I specified above is working perfectly.
