### ISSUE TITLE
How should the play-area resize when changing aspect ratio?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/make-a-ten#49]
Currently, switching from landscape to portrait opens up a ton of room above the numbers:
![making-tens-landscape](https://cloud.githubusercontent.com/assets/480878/11483601/6dfa696c-9766-11e5-845c-23584553c31b.PNG)
![making-tens-portrait](https://cloud.githubusercontent.com/assets/480878/11483604/727fdbde-9766-11e5-8e07-b0078677985c.PNG)

In some past work (for things without an important coordinate-frame), we've resized so that a number at the center of the screen would stay at the center of the screen, and space above/below would expand/contract. I'm fine with either approach, just wanted to mention it.

Other aspect-ratio things that bug me a bit:

On the adding screen, the number input controls and initial numbers are at the bottom:
![making-tens-adding-portrait](https://cloud.githubusercontent.com/assets/480878/11483646/c899566c-9766-11e5-9df4-56a179f98e1c.PNG)

And similarly on the game screen:
![making-tens-game-portrait-1](https://cloud.githubusercontent.com/assets/480878/11483666/e8726280-9766-11e5-9487-fa3e8556f19a.PNG)
![making-tens-game-portrait-2](https://cloud.githubusercontent.com/assets/480878/11483668/eca2f9fa-9766-11e5-9caf-1a590d73fca5.PNG)

**Comment by amanda-phet** [comment]
I agree that the contents of the screen should be centered rather than stay in a fixed location at the bottom of the screen. That would be great to implement.

**Comment by bethstade** [comment]
I agree.

----- Original Message -----From: Amanda McGarry <notifications@github.com>To: phetsims/making-tens <making-tens@noreply.github.com>Sent: Mon, 30 Nov 2015 20:38:16 -0000 (UTC)Subject: Re: [making-tens] How should the play-area resize when changing aspect ratio? (#49)

I agree that the contents of the screen should be centered rather than stay in a fixed location at the bottom of the screen. That would be great to implement.
&mdash;Reply to this email directly or view it on GitHub.
