### ISSUE TITLE
Possible "try the next level" button?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/make-a-ten#92]
Having been vaguely used to other (phet and non-phet) games, just playing with the sim made me feel that sometime the "Next" button might be increasing the level/difficulty.

A "Try the next level" or equivalent button after some number (6?) of correct responses may be a helpful prompt to let the user know "Next doesn't increase the level ever", since there is no "status/current level" information.

@amanda-phet, @bethstade and @ariel-phet, thoughts?

**Comment by jonathanolson** [comment]
@ariel-phet, if this "survives", presumably reassign to another designer?

**Comment by bethstade** [comment]
I would not be inclined to suggest moving levels. While these are games, they are also targeted interventions.  Each is level is very distinct and targets a specific skill.  It is a unique feature of this sim that students can just "add with tens" for example.  The use we would want to see for targeted intervention would be for a student to really focus on one or two levels, not  to race thru the levels as the levels each target a specific "challenge" students have.
What might be useful instead could be a prompt on the lower left arrow that says "Try a DIFFERENT  game," for student who are "playing."

**Comment by amanda-phet** [comment]
I agree with Beth here. The "levels" are skill - based and not exclusively difficulty-based. I like the suggestion to have a different prompt like try a different game, but it might just replace the arrow and return the user to the level selection screen.

Sent from Outlook Mobile<https://aka.ms/blhgte>

**Comment by ariel-phet** [comment]
@bethstade @amanda-phet what do you think about this idea...

Perhaps instead of the current button that appears that says "next --->" we make it more of an iconic button that says " :smile: --->" ?

If feel like that gives that positive "hey look you have done something right, and less of the feeling of "leveling up"

I know that does not fully address @jonathanolson's suggestion of having another button appear after a certain number of tries (but I am not sure I like that idea). It seems once you put that button up there, especially if it pops up after a certain number of tries, it will draw the attention of the student.

What about if you had something like gold stars appear in the upper right hand corner for each correct answer (maybe in some very lightweight panel), and maybe you design the space they go into in such a way that only 8 or 10 stars fit, so you get feedback that you have done things correctly, and then after a certain number you have a subtle cue that maybe it is time to move on to something else.

Not to get too fancy but I was thinking something like once you have 10 stars, a new one slides in and one of the end disappears, so the panel only "holds" 10 stars. After you get 10 you can still see you are getting things correct, but you lose a bit of incentive to collect more.

**Comment by bethstade** [comment]
It sounds to be that the "issues" here are
1. That the "next button" could be suggesting a new level of difficulty (as in other games) when in fact the difficulty remains the same.
2. Considering a "cue" to move on.

Neither of these are a concern for me. In the many months of testing of Snow Day continued interest was not an issue, while teachers would sometimes suggest a different level, one  of the very unique features this sim is that a student can STAY RIGHT WHERE THEY NEED TO BE for a long time.  If you are using the games as a teacher intervention you would not want to be on more than 2 levels - although it is fine to play with as many levels as you want - what is SPECIAL is that it is totally okay and the student is NOT encouraged to move on and can work on very targeted skills.  If a student is having trouble adding with decades, then spending 15 minutes on level 4 without any pressure or incentive to move on is an AMAZING gift and not something a teacher has any other way of doing.

I do agree with Amanda though, that instead of the arrow we could have a message or cue that is more clear that this a return to game choice screen.  "Back to Games" would be okay with me instead of the arrow.  But that is only change I would make.

**Comment by ariel-phet** [comment]
@bethstade one of the reasons I was suggesting the smiley face button was then it does not need to be translated...to me that is an advantage since how translators interpret "next" could change the meaning of that button. I am fine leaving everything else as is, but thoughts on making this an iconic button?

**Comment by bethstade** [comment]
I was thinking about that too. I will come up with some alternatives.

**Comment by bethstade** [comment]
How about an just an arrow on the right when the sum is complete to signal you can move on.  Since the arrow will "pop" out when the sum is complete that should signal, "You did something, you can hang out (and hanging out and playing more with the sum is an encouraged interaction) or move on."
The instead of an arrow on the bottom left, I was thinking of an icon that maps to the Levels Screen with had the 10 squares to signal - "Hey, you can go back and choose another level if you want."
Amy H. helped me with a super quick mock up.
![making_tens_new_buttons](https://cloud.githubusercontent.com/assets/5370001/13716213/f0552002-e796-11e5-9e89-0be139ab67a4.png)

**Comment by ariel-phet** [comment]
@bethstade I am fine with that, but I do think the arrow should be on a button.

**Comment by bethstade** [comment]
I am fine with the arrow on a button.

**Comment by jonathanolson** [comment]
Discussed long ago, and I believe this now shouldn't be an issue with the status bar on the top. Closing.
